# Generated by Django 3.2.5 on 2021-08-09 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_guest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Guest',
        ),
    ]
