# Generated by Django 3.2.5 on 2021-08-13 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='thumbnail',
            field=models.ImageField(blank=True, default=True, upload_to=''),
        ),
    ]
