# Generated by Django 3.2.5 on 2021-08-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='author',
        ),
        migrations.AddField(
            model_name='record',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='period',
            field=models.IntegerField(null=True),
        ),
    ]
