# Generated by Django 3.2.2 on 2021-08-12 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='period',
            field=models.IntegerField(null=True),
        ),
    ]
