# Generated by Django 3.2.5 on 2021-08-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20210811_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
