# Generated by Django 3.2.5 on 2021-08-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_record_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='period',
        ),
        migrations.AddField(
            model_name='record',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
