# Generated by Django 3.2.5 on 2021-08-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_auto_20210812_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='thumbnail',
            field=models.ImageField(default=True, upload_to=''),
        ),
    ]
