# Generated by Django 3.2.5 on 2021-08-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='period',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
