# Generated by Django 3.2.5 on 2021-08-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_challenge_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='thumbnail',
            field=models.ImageField(default=True, upload_to=''),
        ),
    ]
