# Generated by Django 3.2.5 on 2021-08-11 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0005_auto_20210812_0359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='method',
            new_name='detail',
        ),
    ]
