# Generated by Django 3.2.5 on 2021-08-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0006_rename_method_challenge_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='category',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
